POST http://localhost:8080/user/register
Content-Type: application/json

{
  "name": "재민",
  "password": "testpassword123",
  "birthdate": "2005-01-01",
  "major": "AI소프트웨어",
  "grade": "3학년",
  "desiredTrackId": 2,
  "level": "중"
}